# Scapes Indexer - Kamal Deployment Configuration
service: scapes-indexer

image: jwahdatehagh/scapes-indexer

servers:
  web:
    hosts:
      - 46.62.228.203
  cron:
    hosts:
      - 46.62.228.203
    cmd:
      /usr/local/bin/supercronic config/crontab

proxy:
  ssl: true
  host: indexer.scapes.xyz
  app_port: 42069
  healthcheck:
    path: /ready
    # path: /health
    interval: 5
    timeout: 300

deploy_timeout: 300

registry:
  username: jwahdatehagh
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: ..
  dockerfile: ../Dockerfile.indexer

env:
  secret:
    - PONDER_RPC_URL_1
    - PONDER_RPC_URL_1_WS
    - DATABASE_URL
    - OPENSEA_API_KEY
    - DATABASE_SCHEMA
    - PONDER_VIEWS_SCHEMA
    - PONDER_TELEMETRY_DISABLED
    - PUNKSCAPE_DATABASE_URL
    - S3_BUCKET
    - S3_REGION
    - S3_KEY
    - S3_SECRET
    - S3_ENDPOINT
    - S3_PUBLIC_URL
    - G27_SIGNER_PRIVATE_KEY
    - G27V1_SIGNER_PRIVATE_KEY
    - PINATA_JWT
    - PINATA_GATEWAY
    - LEONARDO_KEY
    - TEAM_TOKEN

accessories:
  db:
    image: postgres:17-alpine
    host: 46.62.228.203
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_DB: ponder
        POSTGRES_USER: ponder
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

ssh:
  user: root
